== Introdução

Um dos setores que vem se destacando no segmento turístico é o de
eventos. Nunca é demais lembrar que a realização de um evento movimenta de
forma significativa a cadeia produtiva da cidade que o abriga. E na rede hoteleira
não é diferente, os hotéis vem investindo e implantando o departamento de eventos
em seus empreendimentos, podendo assim, ser um ponto chave para a solução da
sazonalidade. (SENAC 2011).

Não basta só a implantação desse setor na rede hoteleira, precisa-se de uma
estrutura física e organizacional preparada para o recebimento de uma diversidade
de pessoas, fazendo com que todos se sintam iguais e bem acomodados. De acordo
com o censo (2010) 45,6 milhões de pessoas no Brasil, ou seja, 23,9% da
população brasileira possui algum tipo de deficiência. Sendo assim, será que o setor
de eventos da rede hoteleira de João Pessoa está preparado para o recebimento de
clientes especiais? Sabendo que, a participação de deficientes físicos e/ou
mobilidade reduzida tem crescido bastante na prática de turismo e participação em
eventos.footnote:[Adaptado: Shimosakai, Ricardo. Turismo Adaptado:
http://turismoadaptado.wordpress.com/201/10/22/turismo-adaptado-e-debatido-em-forum-da-pessoa-com-deficiencia. 
Acesso em: 21 out. 2013. Disponível:  Acesso em: 21 out. 2013.]

Por isso, o presente trabalho analisou a acessibilidade no setor de eventos
dos hotéis de João Pessoa. O mesmo foi dividido em cinco capítulos, além desta
introdução. No segundo capítulo é abordada a fundamentação teórica que ressalta
os principais tópicos do trabalho desde o início do turismo, dos eventos, da hotelaria
o desenvolvimento turístico da cidade de João Pessoa e o último tópico onde mostra
como deve ser a acessibilidade no setor de eventos. No terceiro capítulo encontram-
se os procedimentos metodológicos necessários para a realização da pesquisa. No
capítulo quatro os resultados obtidos da pesquisa. E por fim, no capítulo cinco as
considerações finais onde ressalta os pontos positivos e negativos deste trabalho.

=== OBJETIVOS

==== Objetivo geral

Analisar a acessibilidade da infraestrutura dos espaços no setor de
eventos dos hotéis associados ao Convention & Visitors Bureau que possuam
mais de cem lugares localizados na cidade de João Pessoa- PB.

==== Objetivos específicos

- Identificar o tipo de evento que é mais realizado nos hotéis;
- Analisar a frequência de clientes com deficiência e/ou mobilidade
reduzida nos eventos;
- Verificar se seus espaços reservados para eventos possuem estrutura
para receber clientes que necessitam de acessibilidade ou são flexíveis para
eventuais adaptações.

=== JUSTIFICATIVA

Diante do crescimento no setor de eventos, percebemos a diversidade de
pessoas que os frequentam, assim, incluindo as pessoas com deficiência ou
mobilidade reduzida. Atualmente existem novas leis para a inclusão desse público
nas empresas, como exemplo da lei de cotas n° 8213/91 para pessoas com
deficiência, onde informa no Art. 93 da lei citada - que a empresa com cem ou mais
funcionários está obrigada a preencher de dois a cinco por cento dos seus cargos
com beneficiários reabilitados, ou pessoas portadoras de deficiência.footnote:[Fonte: Disponível: Deficiente online: <http://www.deficienteonline.com.br/lei-8213-91-lei-de-cotas-para-deficientes-e-pessoas-com-deficiencia___77.html> 
acesso em: 12 mar. 2014.] Sendo assim
muitas empresas procuram esses profissionais para preencherem suas vagas.
Percebe-se que muitas empresas oferecem treinamentos e cursos, como também
realizam reuniões de trabalho, e muitas vezes esses eventos são realizados nos
espaços para eventos dos hotéis, por possuírem facilidades como serviços de
hospedagem e alimentação no mesmo ambiente. Não sendo diferente com as
universidades que promovem eventos científicos com grupos de estudantes que
participam de congressos e palestras, podendo entre o grupo, ter pessoas com
deficiência e/ou mobilidade reduzida. Com isso, mostra a frequência desse público
nos eventos. Então, foi pensado na importância de ser realizado um estudo sobre
esse tema na cidade de João Pessoa, pois, a partir dele iremos identificar se o setor
de eventos da rede hoteleira tem pensado dessa forma e preparado sua
infraestrutura para receber eventos que suportem essa inclusão. Tendo resultados
positivos ou negativos, o trabalho realizado contribuirá para uma visão mais ampla
dos gestores pensando na igualdade, inclusão, conforto e diferencial tanto para a
empresa, quanto para uma cidade que vem crescendo a cada dia.

