== Rascunho

Com o crescimento de pessoas com deficiência e mobilidade reduzida no turismo,
como segmento em destaque encontra-se o setor de eventos. No entanto, buscou-
se realizar um estudo tendo como principal objetivo analisar a acessibilidade da
infraestrutura do setor de eventos nos hotéis associados ao Convention & Visitors
Bureau com espaços acima de cem lugares localizados na cidade de João Pessoa-
PB. Trata-se de uma pesquisa descritiva de caráter quantitativa e qualitativa, e como
instrumento para coleta de dados foi utilizado um questionário com perguntas
fechadas. A partir da análise dos resultados obtidos constatou-se que a
infraestrutura em relação à acessibilidade é relativamente boa, comparando com a
frequência desse público nos eventos que ainda é pequeno na cidade de João
Pessoa PB. Ainda assim, é necessário que os gestores não se acomodem e
continuem aperfeiçoando seus espaços para que no futuro próximo as salas estejam
cem por cento adaptadas para esse público, oferecendo um lugar acessível para
todos, e também tornando um diferencial para sua empresa.
